### ISSUE TITLE
Hanging with contributor skin loading

### ISSUE THREAD

**Issue by Zygus42** [Tamaized/VoidCraft#133]
Would realy like to use this mod on our private server, but it keeps hanging like so:
[New Text Document (2).txt](https://github.com/Tamaized/VoidCraft/files/944147/New.Text.Document.2.txt)

**Comment by Zygus42** [comment]
VoidCraft-1.10.2-0.18.2
TamModized-1.10.2-0.7.1

**Comment by Tamaized** [comment]
In `.minecraft\voidcraft\assets\voidcraft\skins` do all the skins exist there?
If not then that tells me my zip file didn't get unzipped to populate this folder. It exists on servers as well, would be the default `.minecraft` directory on the machine.

![capture](https://cloud.githubusercontent.com/assets/9671313/25241280/465d88d4-25aa-11e7-81ab-94bf8eee0941.PNG)

**Comment by Tamaized** [comment]
Note for myself:
Should prob just loop through the folder and read the files names, compare that to the map keys instead of checking amount of files compared to amount of entries in the map due to this no longer being hardcoded.
https://github.com/Tamaized/VoidCraft/blob/1.11.2/src/main/java/Tamaized/Voidcraft/handlers/SkinHandler.java#L150
