### ISSUE TITLE
No GUI for Voidic Power Generator

### ISSUE THREAD

**Issue by Xman7373** [Tamaized/VoidCraft#147]
![2017-05-20_14 38 48](https://cloud.githubusercontent.com/assets/28369371/26278530/7de84fd2-3d6a-11e7-9a2c-cb94623c5099.png)
As shown, the Voidic Power Generator lacks a GUI—otherwise, the generator functions normally (I had no problem inserting buckets of liquid void).

**Comment by Tamaized** [comment]
Christ this specific issue shows up at random when I push out new builds, I assume 1.10.2?

**Comment by Xman7373** [comment]
Yeah, this is 1.10.2

**Comment by Tamaized** [comment]
Oh good lord, apparently this has been an issue since forever nobody just reported it till now, and for some reason my dev environment isn't case sensitive so these issues get past me, in any case this should be all lowercase https://github.com/Tamaized/VoidCraft/blob/1.10.2/src/main/java/Tamaized/Voidcraft/GUI/client/VoidicPowerGenGUI.java#L18

**Comment by Tamaized** [comment]
Just to confirm, this was the only gui with a texture issue correct?

**Comment by Xman7373** [comment]
Of the machines I've made (void blast furnace, void macerator, void infusion altar, and this) yes.
