### ISSUE TITLE
Game freeze when returning from void

### ISSUE THREAD

**Issue by BaccarWozat** [Tamaized/VoidCraft#158]
Using Forge 2315, VoidCraft 0.19.6, and perhaps importantly, [Cubic Chunks](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2792887-cubic-chunks-mod-almost-infinite-world-height-and) build 0.0.615.0.

Entered void portal at Y=527, got into Void in Y=82. The screen shook for a minute or so (don't know if this is regular behavior) before finally loading anything near me. Went back through the portal and game froze at Loading World screen.

FML Client Latest Log: https://pastebin.com/0DcTtTNU
(lots of redundant lines removed to get this file under 512kb)

![2017-06-11_02 48 40](https://user-images.githubusercontent.com/8357501/27009380-fbfb6fb0-4e51-11e7-8a3d-761c038aeba0.png)
![2017-06-11_02 49 22](https://user-images.githubusercontent.com/8357501/27009379-fbf7b9b0-4e51-11e7-847a-4bbc0bc69620.png)

**Comment by Tamaized** [comment]
Y527 eh? yea that'll def screw with a lot of stuff which I cant fix my end, if you're above, I think it was 257 or so, in the Void you'll be taking Out of World (Vanilla Void) damage. That may explain the shaking, that being the client gets all those damage updates at once after it finishes loading and bam, lots of shaking due to it.

**Comment by Barteks2x** [comment]
Again, this is an issue with how teleporters work in vanilla and that modders need to copypate that class to get portals working. There isn't much I or other mods can do to really fix it.
